[package]
name = "floating-ui-dioxus"
description = "Floating UI for Dioxus."
homepage = "https://floating-ui.rustforweb.org/frameworks/dioxus.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["web"] }
floating-ui-dom.workspace = true
web-sys.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
