name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    rust:
        name: Rust
        uses: RustForWeb/.github/.github/workflows/rust.yml@373c25f8fd29e10c40f1343f13312f8be3514af0
        with:
            enable-test: false
            target: wasm32-unknown-unknown

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
              with:
                  target: wasm32-unknown-unknown
                  components: rust-src

            - name: Install Cargo Binary Install
              uses: cargo-bins/cargo-binstall@dc19f1e48450eefe5a29b8da6c6b00a87d730b37 # v1.18.1

            - name: Install crates
              run: cargo binstall -y --force trunk

            - name: Set up Node.js
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version: 'lts/*'

            - name: Set up pnpm
              uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
              with:
                  version: 'latest'

            - name: Test
              run: cargo test --all-features --locked --release

            - name: Upload visual snapshot diffs
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              if: always()
              with:
                  name: visual-snapshots-diff
                  path: target/tmp/floating-ui/packages/dom/test-results
