name: Check for upstream releases

on:
    schedule:
        - cron: '00 16 * * *'
    workflow_dispatch: {}

permissions:
    contents: read
    pull-requests: write

jobs:
    check:
        name: Check for upstream releases
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: clippy, rustfmt

            - name: Check for upstream releases
              run: cargo run -p scripts --bin upstream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GIT_USER_NAME: github-actions[bot]
                  GIT_USER_EMAIL: github-actions[bot]@users.noreply.github.com
                  RUST_LOG: upstream=debug
