name: Check for upstream releases

on:
    schedule:
        - cron: '00 16 * * *'
    workflow_dispatch: {}

permissions:
    contents: read
    pull-requests: write

jobs:
    check:
        name: Check for upstream releases
        runs-on: ubuntu-latest

        steps:
            - name: Generate GitHub App token
              id: app-token
              uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
              with:
                  client-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0

            - name: Check for upstream releases
              run: cargo run -p scripts --bin upstream
              env:
                  GITHUB_ACTOR: rust-for-web[bot]
                  GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
                  GIT_USER_NAME: rust-for-web[bot]
                  GIT_USER_EMAIL: 191031261+rust-for-web[bot]@users.noreply.github.com
                  RUST_LOG: upstream=debug
