name: Check for upstream releases

on:
    schedule:
        - cron: '00 16 * * *'
    workflow_dispatch: {}

permissions:
    contents: read
    pull-requests: write

jobs:
    check:
        name: Check for upstream releases
        runs-on: ubuntu-latest

        steps:
            - name: Generate GitHub App token
              id: app-token
              uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
              with:
                  client-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Set up Rust toolchain
              uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0

            - name: Check for upstream releases
              run: cargo run -p scripts --bin upstream
              env:
                  GITHUB_ACTOR: rust-for-web[bot]
                  GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
                  GIT_USER_NAME: rust-for-web[bot]
                  GIT_USER_EMAIL: 191031261+rust-for-web[bot]@users.noreply.github.com
                  RUST_LOG: upstream=debug
