name: Website

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read
    id-token: write
    pages: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    book:
        name: Book
        uses: RustForWeb/.github/.github/workflows/book.yml@373c25f8fd29e10c40f1343f13312f8be3514af0
